// <auto-generated />
namespace MvcGestionAsso.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FormuleNoDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FormuleNoDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201509182034474_FormuleNoDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
